image: node:4.4.6

before_script:
    - rm -rf node_modules
    - npm install --no-optional

test:
    services:
        - mongo
    script:
        - npm test

build:
    script:
        - gulp build
