language: node_js
sudo: yes
node_js:
  - 4.4.6
before_install:
env:
  - CXX=gcc++-4.8
install:
  - npm install --no-optional
services: mongodb
script:
  - npm test
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
