language: node_js
sudo: yes
node_js:
  - latest
matrix:
  fast_finish: true
before_script:
  - rm -rf node_modules
  - npm install -g npm@latest
  - npm rebuild node-sass
  - npm install --no-optional
services: mongodb
script:
  - npm test
