language: node_js
sudo: yes
node_js:
  - latest
matrix:
  fast_finish: true
before_script:
  - npm prune
  - npm install -g npm@latest
  - npm install -g gulp-cli
  - gulp build
  - npm install --no-optional
services: mongodb
script:
  - npm test
