language: node_js
sudo: yes
node_js:
  - 4.4.6
before_install:
  - rm -rf node_modules
  - echo "yes" | sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get -y update -qq
  - sudo apt-get -y install -qq g++-4.8
  - sudo apt-get install -y libstdc++-4.8-dev
env:
  - CXX="gcc++-4.8"
  - CC="gcc-4.8"
install:
  - npm install --no-optional
services: mongodb
script:
  - npm test
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - gcc-4.8
      - clang
