language: node_js
sudo: yes
node_js:
  - 4.4.6
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  - rm -rf node_modules
env:
  - CXX="g++-4.8"
install:
  - npm install --no-optional
services: mongodb
script:
  - npm test
