language: node_js
sudo: yes
node_js:
  - 4.4.6
before_script:
  - rm -rf node_modules
  - npm install iltorb
before_install:
  - npm install -g npm@3.10.8
install:
  - npm install --no-optional
services: mongodb
script:
  - npm test
