language: node_js
sudo: yes
node_js:
  - 6.7.0
before_script:
  - apt-get install -y build-essential
  - rm -rf node_modules
  - npm install -g npm@latest
  - npm rebuild node-sass
  - npm install --no-optional
install:
  - npm install --no-optional
services: mongodb
script:
  - npm test
